/* eslint-disable no-unused-vars */
export enum IconEnum {
  Search = "Search",
  SearchSmall = "SearchSmall",
  ArrowRight = "ArrowRight",
  ArrowRightSmall = "ArrowRightSmall",
  ArrowRightBig = "ArrowRightBig",
  Like = "Like",
  Download = "Download",
  Eye = "Eye",
  Hair = "Hair",
  Skin = "Skin",
  Calendar = "Calendar",
  polygon = "Polygon",
  Crown = "Crown",
  Mirror = "Mirror",
  discord = "Discord",
  Cross = "Cross",
  Cube = "Cube",
  CubeWithCircle = "CubeWithCircle",
  Note = "Note",
  Shop = "Shop",
  ethereum = "Ethereum",
  youtube = "Youtube",
  instagram = "Instagram",
  linkedin = "Linkedin",
  twitter = "XTwitter",
  sepolia = "sepolia",
}
